@startuml
left to right direction
actor Empleado as emp
(Alta Cliente) as Ac
(Introducir pedido) as Ip
(Obtener\nEstado\nPedido) as Oep
(Buscar Pedido) as Bp
(Cancelar Pedido) as Cp

emp -- Ac
emp -- Ip
emp -- Oep
emp -- Bp
emp -- Cp
Ac ..> Ip : <<extends>>
Oep ..> Bp : <<include>>
Cp ..> Bp : <<include>>
Ip ..> (Buscar Cliente) : <<include>>
(Pago con\ntarjeta) <.left. Ip : <<extends>>
(Pago en\ncuenta) <.. Ip : <<extends>>
@enduml